project_id = "trbvlmzrnopvubizaacb"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.import-kaggle-cosmetics]
verify_jwt = false

[functions.gcs-file-manager]
verify_jwt = false

[functions.import-gcs-dataset]
verify_jwt = false

[functions.match-foundations]
verify_jwt = false